[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

# Libraries
lib_deps =
    U8g2
    AHT10
    OneWire
    DallasTemperature
    ESPAsyncTCP
    ESPAsyncWebServer

build_flags =
    -DDEBUG_ESP_PORT=Serial
